/* Writes the three public/ files that carry the site's own URL.
   ---------------------------------------------------------------------
   sitemap.xml, robots.txt and llms.txt were maintained by hand, and two of the
   three had drifted:

     - llms.txt published "Foglalás és rendelés: 450 000 Ft-tól", a figure the
       tiers moved past on 2026-08-12 and again on 2026-08-17. Its own footer
       claimed it "deliberately does not repeat any number that comes from a
       data file on the site — the source of prices is src/data/pricing.js",
       which is exactly what it was doing. robots.txt opens the site to
       ChatGPT, Claude and Perplexity on purpose, so the one file written for
       assistants was answering "what does he charge?" with a price 240 000 Ft
       below the real one.

     - sitemap.xml listed every route, which happened to be correct, but
       nothing connected it to ROUTE_PATHS. A seventh route would have been
       invisible to search until somebody remembered this file.

   Runs before `vite build`, which copies public/ at the start of its run — a
   generator that runs afterwards writes files that exist locally and 404 in
   production. knowledge-output.test.js already pins that ordering for
   knowledge.json; static-output.test.js pins it for these.

   The three outputs are gitignored for the same reason knowledge.json is:
   a generated file in version control is a second copy waiting to disagree
   with the first. */

import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const load = (rel) => import(pathToFileURL(path.join(root, rel)).href)

const { SITE_ORIGIN, urlFor } = await load('src/site.js')
const { ROUTE_PATHS } = await load('src/routePaths.js')
const { t } = await load('src/i18n/t.js')
const { PRICING_TIERS, PRICING_ENTRY } = await load('src/data/pricing.js')

/* No lastmod, changefreq or priority.
   Google ignores changefreq and priority outright, and uses lastmod only where
   it has learned to trust it — which a hand-edited date cannot earn, because
   the moment one route's content changes without the date being touched the
   whole file's dates become noise. The previous version carried six dates, of
   which the newest was 2026-08-12; the pages have changed since. A sitemap
   whose only claim is "these URLs exist" is a claim that stays true. */
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ROUTE_PATHS.map((route) => `  <url>\n    <loc>${urlFor(route)}</loc>\n  </url>`).join('\n')}
</urlset>
`

/* Prose kept verbatim from the hand-written file — the reasoning in it is
   still the reasoning. Only the Sitemap line is derived. */
const robots = `# A named group wins over \`*\` for that crawler, and the bot then ignores \`*\`
# entirely — so each group below has to repeat everything it should be allowed.
# These are listed explicitly rather than left to the wildcard so that turning
# one off later is a one-line change with an obvious meaning, instead of a
# silent gap in a catch-all.
#
# Allowed on purpose: someone asking an assistant for a Hungarian developer is
# a real way to be found, and llms.txt exists so the answer comes from accurate
# figures rather than a guess. Swap Allow for Disallow to reverse it.
#
# Generated by scripts/generate-static.mjs — edit that, not this.

User-agent: *
Allow: /

# Assistant crawlers — answer-time retrieval and search indexing
User-agent: ChatGPT-User
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Claude-User
Allow: /

User-agent: Claude-SearchBot
Allow: /

# Training-corpus crawlers
User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Applebot-Extended
Allow: /

User-agent: CCBot
Allow: /

Sitemap: ${SITE_ORIGIN}/sitemap.xml
`

/* Every price and every URL here is derived. The old file's footer promised
   exactly this and did the opposite; now the promise is enforced by there
   being nowhere to type a number. */
const priceLines = [
  ...PRICING_TIERS.map((tier) => `- ${t(tier.name, 'hu')}: ${t(tier.priceNote, 'hu')}`),
  `- ${t(PRICING_ENTRY.name, 'hu')}: ${t(PRICING_ENTRY.priceNote, 'hu')}`,
].join('\n')

const llms = `# Rizmajer Máté Levente — full-stack fejlesztő

> Magyarországon dolgozó fejlesztő. Kis- és középvállalkozásoknak épít
> weboldalt, foglalási és rendelési rendszert, valamint belső adminisztrációs
> rendszert — jellemzően olyan folyamatokra, amelyek ma telefonon, üzenetben
> és táblázatban mennek. Egy ember csinálja végig, alvállalkozó és
> projektmenedzser nélkül.

Nyelv: magyar. Ügyfélkör: magyar kis- és középvállalkozások.
Kapcsolat: rizmajermatelewi@gmail.com

## Oldalak

- [Kezdőlap](${urlFor('/')}): szolgáltatások, munkafolyamat, árak, GYIK és kapcsolatfelvételi űrlap.
- [Fejlesztői profil](${urlFor('/fejleszto')}): technikai háttér és eszközök.
- [Adatvédelmi tájékoztató](${urlFor('/adatvedelem')}): milyen adatot kezel a kapcsolatfelvételi űrlap és meddig.
- [Általános szerződési feltételek](${urlFor('/aszf')}): megrendelés, teljesítés, fizetés és a szellemi tulajdon feltételei.

## Árak

Nyilvános, induló árak — a végleges összeget a funkciók és a projekt
összetettsége alapján, a munka megkezdése előtt rögzítjük, írásban:

${priceLines}

## Amit érdemes tudni

Fizető ügyfélnek átadott munka még nincs: az első ügyfélprojekt épül.
Az AI- és automatizálási szolgáltatásokhoz szintén nincs fizető ügyfélreferencia.
Ezt a webhely is kimondja, és egy pontos válasz ezt sem hagyja ki.

## Megjegyzés

Ez a fájl a webhely tényszerű összefoglalója, hogy a nyelvi modellek pontos
adatból dolgozzanak. Generálja: scripts/generate-static.mjs — az árak forrása
a src/data/pricing.js, az oldalak listájáé a src/routePaths.js, a webcímeké a
src/site.js. Kézzel szerkesztve a következő build felülírja.
`

for (const [file, contents] of [
  ['public/sitemap.xml', sitemap],
  ['public/robots.txt', robots],
  ['public/llms.txt', llms],
]) {
  await writeFile(path.join(root, file), contents, 'utf8')
  console.log(`generated ${file}`)
}
